In [2]:
import pandas as pd
import numpy as np
import pickle
import json

df = pd.read_csv('anilist_anime_data_complete.csv')

In [3]:
df = df[df['popularity'] > 30000]
df = df[df['isAdult'] == False]
df = df.reset_index()
df = df[['title_romaji', 'coverImage_large', 'id', 'genres', 'tags']]

In [4]:
for tags in range(len(df['tags'].apply(json.loads))):
    for tag in df['tags'].apply(json.loads)[tags]:
        if tag['rank'] > 75 and tag['isAdult'] == False:
            if tag['name'] not in df.columns:
                df[tag['name']] = 0
            df[tag['name']][tags] = tag['rank']

C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[tag['name']][tags] = tag['rank']
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\1220729427.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame


In [5]:
for genres in range(len(df['genres'].apply(json.loads))):
    for genre in df['genres'].apply(json.loads)[genres]:
            if genre not in df.columns:
                df[genre] = 0
            df[genre][genres] = 1

C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:4: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[genre] = 0
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\906486332.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[genre][genres] = 1

In [6]:
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

C:\Users\Aryan\anaconda3\envs\connection\lib\site-packages\scipy\__init__.py:155: UserWarning: A NumPy version >=1.18.5 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
  warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"

In [24]:
df.head()

,title_romaji,coverImage_large,id,genres,tags,Boxing,Coming of Age,Delinquents,Tragedy,Male Protagonist,...,Romance,Mystery,Fantasy,Horror,Supernatural,Psychological,Music,Ecchi,Mahou Shoujo,Thriller
0,Ashita no Joe,https://s4.anilist.co/file/anilistcdn/media/an...,2402,"[""Action"", ""Drama"", ""Slice of Life"", ""Sports""]","[{""id"": 169, ""name"": ""Boxing"", ""description"": ...",90,90,87,83,80,...,0,0,0,0,0,0,0,0,0,0
1,Lupin III,https://s4.anilist.co/file/anilistcdn/media/an...,1412,"[""Adventure"", ""Comedy""]","[{""id"": 50, ""name"": ""Seinen"", ""description"": ""...",0,0,0,0,80,...,0,0,0,0,0,0,0,0,0,0
2,Kidou Senshi Gundam,https://s4.anilist.co/file/anilistcdn/media/an...,80,"[""Drama"", ""Mecha"", ""Sci-Fi""]","[{""id"": 111, ""name"": ""War"", ""description"": ""Pa...",0,80,0,80,0,...,0,0,0,0,0,0,0,0,0,0
3,Versailles no Bara,https://s4.anilist.co/file/anilistcdn/media/an...,338,"[""Adventure"", ""Drama"", ""Romance""]","[{""id"": 25, ""name"": ""Historical"", ""description...",0,0,0,97,0,...,1,0,0,0,0,0,0,0,0,0
4,Lupin III: Cagliostro no Shiro,https://s4.anilist.co/file/anilistcdn/media/an...,1430,"[""Action"", ""Adventure"", ""Comedy"", ""Mystery""]","[{""id"": 648, ""name"": ""Crime"", ""description"": ""...",0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [63]:
df.reset_index(inplace=True)

In [69]:
df.drop(columns=['index'], inplace=True)

In [70]:
cosine_sim = linear_kernel(df.iloc[:, 5:], df.iloc[:, 5:])

In [71]:
np.save('matrix.npy', cosine_sim)

In [72]:
import numpy as np
with open('matrix.npy', 'rb') as f:
    cosine_sim = np.load(f)
cosine_sim

array([[4.3462e+04, 1.4160e+04, 1.3841e+04, ..., 6.7210e+03, 6.9620e+03,
        6.3230e+03],
       [1.4160e+04, 6.2357e+04, 0.0000e+00, ..., 1.8888e+04, 6.9600e+03,
        1.5239e+04],
       [1.3841e+04, 0.0000e+00, 9.5694e+04, ..., 1.9807e+04, 2.0000e+00,
        2.0000e+00],
       ...,
       [6.7210e+03, 1.8888e+04, 1.9807e+04, ..., 7.5438e+04, 2.2704e+04,
        6.6390e+03],
       [6.9620e+03, 6.9600e+03, 2.0000e+00, ..., 2.2704e+04, 8.5140e+04,
        6.8770e+03],
       [6.3230e+03, 1.5239e+04, 2.0000e+00, ..., 6.6390e+03, 6.8770e+03,
        6.7298e+04]])

In [92]:
indices = df[['title_romaji', 'coverImage_large', 'id', 'genres', 'tags']]

In [124]:
json.loads(indices['genres'][0])

'Action'

In [127]:
for index, row in indices.iterrows():
    clean_tags = []
    for tag in json.loads(row['tags']):
        if len(clean_tags) < 5:
            print(tag['name'])
            clean_tags.append(tag['name'])
    indices['tags'][index] = clean_tags
    clean_genres = []
    for genre in json.loads(row['genres']):
        clean_genres.append(genre)
    indices['genres'][index] = clean_genres

Boxing
Coming of Age
Delinquents
Tragedy
Male Protagonist
Seinen
Anti-Hero
Fugitive
Episodic
Crime
War
Military
Real Robot
Space
Space Opera
Historical
Royal Affairs
Class Struggle
Tragedy
Foreign
Crime
Conspiracy
Fugitive
Anti-Hero
Foreign
Environmental
Post-Apocalyptic
Female Protagonist
Lost Civilization
Philosophy
Vampire
Body Horror
Travel
Monster Girl
Primarily Adult Cast
Philosophy
Dystopian
Lost Civilization
Religion
Mythology
Martial Arts
Post-Apocalyptic
Tragedy
Super Power
Male Protagonist
Space Opera
War
Space
Military
Love Triangle
Episodic
Urban Fantasy
Aliens
Heterosexual
Slapstick
Cyberpunk
Post-Apocalyptic
Dystopian
Super Power
Urban
Gender Bending
Family Life
Martial Arts
Slapstick
Heterosexual
Shounen
Martial Arts
Super Power
Travel
Coming of Age
Coming of Age
Witch
Urban Fantasy
Female Protagonist
Magic
Lost Civilization
Steampunk
Pirates
Environmental
Aviation
Family Life
Primarily Child Cast
Rural
Youkai
Wilderness
Tragedy
Orphan
War
Family Life
Survival
Shounen
Super Power
Martial Arts
Henshin
Male Protagonist
Space Opera
Politics
War
Military
Space
Shounen
Super Power
Martial Arts
Male Protagonist
Gods
Shounen
Super Power
Aliens
Martial Arts
Male Protagonist
Space
Female Protagonist
Military
War
Coming of Age
Shounen
Primarily Male Cast
Mythology
Male Protagonist
Gods
Philosophy
Coming of Age
Tragedy
Super Robot
Dystopian
Cyberpunk
Artificial Intelligence
Philosophy
Urban
Robots
Politics
Space
Military
Real Robot
War
Basketball
Shounen
School
Primarily Teen Cast
School Club
Episodic
Work
Seinen
Satire
Male Protagonist
Coming of Age
Shounen
Demons
Philosophy
Super Power
Aviation
Foreign
Anthropomorphism
Historical
Philosophy
Magic
Shoujo
Female Protagonist
Henshin
Primarily Female Cast
Shoujo
Magic
Henshin
Female Protagonist
Urban Fantasy
Magic
Swordplay
Female Protagonist
Anti-Hero
Medieval
Coming of Age
Writing
Female Protagonist
Heterosexual
Shoujo
Ninja
Historical
Gore
Swordplay
Heterosexual
Shounen
Super Power
Vampire
Primarily Male Cast
Body Horror
Magic
Female Protagonist
Primarily Female Cast
Shoujo
Henshin
School
Coming of Age
Male Protagonist
Heterosexual
Love Triangle
Shounen
Super Power
Martial Arts
Aliens
Male Protagonist
Martial Arts
Shounen
Super Power
Aliens
Male Protagonist
Martial Arts
Super Power
Shounen
Aliens
Henshin
Robots
Shounen
Super Power
Male Protagonist
Martial Arts
Shounen
Super Power
Martial Arts
Aliens
Male Protagonist
Super Power
Martial Arts
Shounen
Aliens
Male Protagonist
Super Power
Shounen
Aliens
Martial Arts
Demons
Shounen
Super Power
Aliens
Male Protagonist
Martial Arts
Shounen
Super Power
Demons
Male Protagonist
Martial Arts
Martial Arts
Shounen
Demons
Super Power
Aliens
Female Protagonist
Iyashikei
Rural
Coming of Age
Biographical
Environmental
Mythology
Ensemble Cast
Animals
Rural
Anthology
Steampunk
Dystopian
Politics
Seinen
Space
Crime
Episodic
Ensemble Cast
Primarily Adult Cast
Guns
Fugitive
Male Protagonist
Philosophy
Primarily Adult Cast
Pirates
Travel
Shounen
Ensemble Cast
Super Power
Primarily Teen Cast
Achronological Order
Tragedy
Dystopian
Super Robot
Philosophy
Tragedy
Coming of Age
Post-Apocalyptic
Meta
Tragedy
Seinen
Swordplay
War
Male Protagonist
Samurai
Tragedy
Historical
Revenge
Philosophy
Swordplay
Martial Arts
Samurai
Historical
Heterosexual
Shounen
Ensemble Cast
Super Power
Cultivation
Urban Fantasy
Coming of Age
Heterosexual
School
Shoujo
Primarily Teen Cast
Tragedy
Dystopian
War
Slavery
Survival
Environmental
Mythology
Animals
Philosophy
War
Isekai
Lost Civilization
Love Triangle
Dragons
Travel
Cars
Male Protagonist
CGI
Rural
Primarily Male Cast
Cars
Seinen
Primarily Male Cast
Rural
Male Protagonist
Female Harem
Heterosexual
Cohabitation
Love Triangle
College
Aliens
Age Regression
Henshin
Space
Dragons
Coming of Age
Surreal Comedy
Psychosexual
Male Protagonist
Age Gap
Magic
Shoujo
Female Protagonist
Urban Fantasy
Primarily Child Cast
Detective
Crime
Espionage
Tragedy
Age Regression
Teacher
School
Work
Delinquents
Male Protagonist
Youkai
Reincarnation
Demons
Historical
Female Protagonist
Boxing
Male Protagonist
Primarily Male Cast
Shounen
Martial Arts
Denpa
Philosophy
Virtual World
Dissociative Identities
Augmented Reality
Denpa
Achronological Order
Urban Fantasy
Philosophy
Dissociative Identities
Space
Artificial Intelligence
Assassins
Aliens
Male Protagonist
Dissociative Identities
Denpa
Female Protagonist
Acting
Idol
Coming of Age
Female Protagonist
Psychosexual
Philosophy
Fairy Tale
Pirates
Super Power
Shounen
Ensemble Cast
Male Protagonist
Card Battle
Shounen
Proxy Battle
Reincarnation
Historical
Proxy Battle
Travel
Creature Taming
Animals
Primarily Child Cast
Animals
Philosophy
Tragedy
Proxy Battle
Clone
Vampire
Male Protagonist
Primarily Adult Cast
Dystopian
Fugitive
Death Game
Shounen
Dissociative Identities
Card Battle
Henshin
Isekai
Virtual World
Primarily Child Cast
Proxy Battle
Ensemble Cast
Conspiracy
Tragedy
Philosophy
Police
Espionage
Male Protagonist
Dragons
Mythology
Ships
Coastal
Animals
Creature Taming
Kids
Male Protagonist
Family Life
Ghost
Primarily Child Cast
School
Episodic
Youkai
Artificial Intelligence
Primarily Child Cast
Virtual World
Kaiju
Proxy Battle
Terrorism
Primarily Adult Cast
Philosophy
Crime
Martial Arts
American Football
School Club
Male Protagonist
School
Shounen
Coming of Age
College
Male Protagonist
Urban
Primarily Adult Cast
Cars
Rural
Seinen
CGI
Primarily Adult Cast
Crime
Seinen
Detective
Ensemble Cast
Fugitive
Ninja
Shounen
Criminal Organization
Coming of Age
Male Protagonist
Tennis
Male Protagonist
Primarily Male Cast
School Club
Shounen
Ensemble Cast
Love Triangle
School
Delinquents
Primarily Teen Cast
Dystopian
Cyberpunk
Philosophy
Noir
Tragedy
Virtual World
Female Protagonist
Video Games
Anti-Hero
Gender Bending
Band
Coming of Age
Urban
Rock Music
Male Protagonist
Artificial Intelligence
Amnesia
Robots
Memory Manipulation
Seinen
Demons
Historical
Nun
Tragedy
Female Protagonist
Seinen
Ojou-sama
Magic
Urban Fantasy
Primarily Female Cast
Episodic
School
Primarily Female Cast
Slapstick
Surreal Comedy
Ninja
Seinen
Historical
Primarily Adult Cast
Martial Arts
Super Power
Assassins
Revenge
Guns
Tragedy
Military
Guns
Real Robot
Love Triangle
Heterosexual
Slapstick
School
Tsundere
Surreal Comedy
Parody
Military
Guns
Heterosexual
Nudity
Foreign
Female Harem
Primarily Female Cast
Demons
Urban Fantasy
Gods
Military
War
Tragedy
Real Robot
Space
Aviation
War
Post-Apocalyptic
Steampunk
Female Protagonist
Tragedy
Reincarnation
Historical
Magic
Homeless
Surreal Comedy
Delinquents
School
Primarily Male Cast
Ensemble Cast
Family Life
Mythology
Shoujo
Female Protagonist
Male Harem
Alchemy
Philosophy
Magic
Tragedy
Male Protagonist
Guns
Assassins
Foreign
Female Protagonist
Terrorism
Super Power
Card Battle
Shounen
Male Protagonist
Cultivation
Vampire
Female Protagonist
Swordplay
Demons
Found Family
Isekai
Female Protagonist
Coming of Age
Politics
Language Barrier
Shounen
Ghost
Super Power
Male Protagonist
Mythology
Vampire
Super Power
Adoption
Urban Fantasy
Amnesia
Martial Arts
School
Delinquents
Male Protagonist
Tragedy
Isekai
Magic
Shounen
Alternate Universe
Heterosexual
Cars
Primarily Male Cast
Seinen
Male Protagonist
Rural
Teacher
Aliens
Age Gap
Coming of Age
Ensemble Cast
Female Protagonist
Youkai
Coming of Age
Curses
Magic
Survival
Animals
Primarily Male Cast
Dystopian
Tragedy
Travel
Swordplay
Samurai
Rural
Assassins
Gore
Fugitive
Super Power
Amnesia
Monster Girl
Revenge
Episodic
Female Protagonist
Tragedy
Bullying
Environmental
Coming of Age
Politics
Found Family
Super Robot
Revenge
Classic Literature
Urban
Urban Fantasy
Tragedy
Otaku Culture
School Club
Parody
College
Cosplay
Space
Age Gap
Achronological Order
Male Protagonist
Coming of Age
Martial Arts
Nudity
Female Protagonist
Female Harem
Tomboy
Boxing
Martial Arts
Shounen
Male Protagonist
Coming of Age
Crime
Mafia
Gangs
Male Protagonist
Tragedy
Swordplay
Shounen
Super Power
Afterlife
Ghost
Vampire
Primarily Adult Cast
Super Power
Noir
Gore
Martial Arts
Male Protagonist
Primarily Male Cast
Cultivation
Shounen
Coming of Age
Fashion
Josei
Makeup
Female Protagonist
Denpa
Crime
Philosophy
Detective
Urban Fantasy
Space
Work
Primarily Adult Cast
Philosophy
Seinen
Surreal Comedy
Shounen
School
Heterosexual
Delinquents
Super Power
Urban Fantasy
Tsundere
Anti-Hero
Love Triangle
Surreal Comedy
Gore
Parody
Slapstick
Assassins
Family Life
Tragedy
Monster Girl
Urban Fantasy
Seinen
Death Game
Body Horror
Gore
Aliens
Afterlife
Angels
Rehabilitation
Philosophy
Found Family
Female Protagonist
Historical
Shounen
Foreign
Alternate Universe
Male Protagonist
Magic
Female Protagonist
Steampunk
Witch
Elderly Protagonist
Heterosexual
Alternate Universe
Military
Aviation
Coming of Age
Ninja
Shounen
Super Power
Male Protagonist
Primarily Child Cast
Environmental
Iyashikei
Youkai
Mythology
Episodic
Pirates
Ensemble Cast
Male Protagonist
Revenge
Shounen
Cyberpunk
Police
Episodic
Robots
Politics
Philosophy
Cyberpunk
Police
Memory Manipulation
Artificial Intelligence
Iyashikei
Ships
Work
Philosophy
Female Protagonist
Card Battle
School
Male Protagonist
Primarily Teen Cast
Coming of Age
Philosophy
Episodic
Travel
Foreign
Tragedy
Cute Girls Doing Cute Things
Primarily Female Cast
Primarily Child Cast
Female Protagonist
School
Robots
Dystopian
Artificial Intelligence
Fugitive
Detective
Anthropomorphism
Animals
Fairy Tale
Female Protagonist
Nekomimi
Gambling
Mahjong
Noir
Death Game
Seinen
Henshin
Female Protagonist
Environmental
Aliens
Primarily Female Cast
Fairy Tale
Ballet
Dancing
Philosophy
Meta
Found Family
Homeless
Estranged Family
Urban
Family Life
Police
Politics
Cyberpunk
Terrorism
Military
Primarily Child Cast
Virtual World
Artificial Intelligence
Tragedy
Denpa
Ninja
Shounen
Super Power
Male Protagonist
Lost Civilization
Acting
Biographical
Historical
Primarily Adult Cast
Female Protagonist
Time Manipulation
Animals
Rural
Outdoor Activities
Fairy
Animals
Kids
Ships
Proxy Battle
Creature Taming
Aliens
Dragons
Animals
Ensemble Cast
Creature Taming
Kids
Animals
Proxy Battle
Creature Taming
Travel
Proxy Battle
Animals
Kids
Outdoor Activities
Episodic
Magic
Battle Royale
Death Game
Urban Fantasy
Mythology
Vampire
Gore
Seinen
War
Urban Fantasy
Post-Apocalyptic
Philosophy
Dissociative Identities
Dystopian
Clone
School Club
Achronological Order
Urban Fantasy
Gods
School
School Club
Shoujo
Crossdressing
Parody
Surreal Comedy
Yuri
Love Triangle
School
Boarding School
Primarily Teen Cast
War
Amnesia
Post-Apocalyptic
Kemonomimi
Politics
Male Protagonist
Shounen
Parkour
Urban
Delinquents
Mythology
Urban Fantasy
Youkai
Male Protagonist
Philosophy
Female Protagonist
Shoujo
Primarily Adult Cast
Coming of Age
Band
Ensemble Cast
Crime
Guns
Seinen
Primarily Adult Cast
Parody
Ensemble Cast
Samurai
Found Family
Slapstick
Denpa
Alternate Universe
Ensemble Cast
Time Manipulation
Tragedy
Isekai
Magic
Tsundere
Heterosexual
Swordplay
Hikikomori
Rehabilitation
Otaku Culture
Male Protagonist
Denpa
Shoujo
Female Protagonist
Love Triangle
Coming of Age
Tragedy
Revenge
Swordplay
Gore
Samurai
Male Protagonist
Shounen
Demons
Male Protagonist
Super Power
Exorcism
Crime
Guns
Anti-Hero
Gangs
Tomboy
Amnesia
Primarily Female Cast
School
Snowscape
Tragedy
Crime
Detective
Anti-Hero
Fugitive
Male Protagonist
Martial Arts

C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\3514931279.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  indices['tags'][index] = clean_tags
C:\Users\Aryan\AppData\Local\Temp\ipykernel_5640\3514931279.py:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  indices['genres'][index] = clean_genres

Male Protagonist
School
Shounen
Delinquents
Primarily Child Cast
Kids
Male Protagonist
Proxy Battle
Outdoor Activities
Ghost
Detective
Denpa
Youkai
Tragedy
Anti-Hero
War
Military
Politics
Class Struggle
Mafia
Shounen
Super Power
Male Protagonist
Primarily Male Cast
Super Power
Afterlife
Shounen
Swordplay
Male Protagonist
Coming of Age
Heterosexual
Unrequited Love
Time Skip
Tragedy
Tragedy
Ensemble Cast
Super Robot
Alternate Universe
Death Game
Magic
Tsundere
Urban Fantasy
Heterosexual
Incest
Primarily Adult Cast
Josei
Classical Music
College
Male Protagonist
Tragedy
Classic Literature
Politics
Revenge
Historical
School
Rehabilitation
Heterosexual
Primarily Teen Cast
School Club
Demons
Male Protagonist
Body Horror
Video Games
Guns
Ninja
Shounen
Criminal Organization
Male Protagonist
Super Power
Medieval
Swordplay
Female Protagonist
Revenge
Tragedy
Spearplay
Fugitive
Mythology
Female Protagonist
Prophecy
Magic
Medieval
Male Protagonist
Dragons
Dissociative Identities
Isekai
Magic
Tsundere
War
Slavery
Cute Girls Doing Cute Things
Female Protagonist
Primarily Female Cast
Otaku Culture
Parody
Denpa
Time Loop
Alternate Universe
Time Manipulation
Conspiracy
Dissociative Identities
Female Protagonist
Primarily Adult Cast
Philosophy
Body Horror
Super Robot
Coming of Age
Found Family
Male Protagonist
Post-Apocalyptic
Super Power
Anti-Hero
Crime
Noir
Urban
Parody
Meta
Butler
Shounen
Otaku Culture
Female Protagonist
Shoujo
School
Primarily Teen Cast
Slapstick
Parody
Mermaid
Male Protagonist
School
Gangs
Ninja
Male Protagonist
Primarily Male Cast
Circus
Animals
Found Family
Coming of Age
Gangs
Crime
Orphan
Augmented Reality
Urban
Primarily Child Cast
Female Protagonist
Tragedy
Coming of Age
School
Ensemble Cast
Family Life
Urban Fantasy
Time Manipulation
Coming of Age
Female Protagonist
Heterosexual
School
Youkai
Demons
Ghost
Exorcism
Historical
Mafia
Ensemble Cast
Crime
Achronological Order
Alchemy
Swordplay
Historical
Fugitive
Rural
Samurai
Shounen
Ninja
Super Power
Male Protagonist
Demons
Netorare
Hypersexuality
Love Triangle
Female Harem
School
Ensemble Cast
Real Robot
Terrorism
Military
Politics
Suicide
Urban
Female Protagonist
Urban Fantasy
Ghost
Denpa
Ghost
Rural
Dissociative Identities
Cosmic Horror
Satire
Episodic
Surreal Comedy
Teacher
Suicide
Post-Apocalyptic
Coming of Age
Super Robot
Dystopian
Male Protagonist
Tsundere
School
Super Power
Urban Fantasy
Love Triangle
Primarily Child Cast
Dragons
Animals
Proxy Battle
Creature Taming
Shounen
Afterlife
Male Protagonist
Super Power
Swordplay
Primarily Child Cast
Shoujo
Magic
Henshin
Female Protagonist
Amnesia
Twins
Heterosexual
Love Triangle
Rehabilitation
School
Tragedy
Twins
Amnesia
Suicide
Family Life
Primarily Female Cast
Slapstick
Cute Girls Doing Cute Things
School
Police
Detective
Anti-Hero
Gods
Kuudere
Gambling
Survival
Primarily Adult Cast
Class Struggle
Primarily Male Cast
Dissociative Identities
Kuudere
Female Protagonist
Achronological Order
Anti-Hero
Love Triangle
School
Heterosexual
Drawing
Basketball
Coastal
Natural Disaster
Primarily Child Cast
Kids
Environmental
Anti-Hero
War
Military
Class Struggle
Revenge
Medieval
Economics
Male Protagonist
Primarily Adult Cast
Work
School
Monster Girl
Male Protagonist
Female Harem
Vampire
Urban Fantasy
Kaiju
Aliens
Shapeshifting
Primarily Teen Cast
Boys' Love
Primarily Male Cast
LGBTQ+ Themes
Primarily Adult Cast
Josei
Robots
Artificial Intelligence
Philosophy
Bar
Male Protagonist
Satire
Surreal Comedy
Parody
Teacher
School
Coming of Age
Iyashikei
Ships
Philosophy
Work
Female Protagonist
Primarily Adult Cast
Cosmic Horror
Guns
Rape
Female Harem
Slapstick
Surreal Comedy
Nudity
Aliens
Shoujo
Vampire
Female Protagonist
School
Boarding School
Shoujo
Ensemble Cast
School
Tsundere
School Club
Female Harem
Love Triangle
Twins
Youkai
Nudity
Super Power
Ensemble Cast
Shounen
Magic
School
Alternate Universe
Denpa
Rural
Twins
Shrine Maiden
Kemonomimi
Military
Female Protagonist
Aviation
Primarily Female Cast
Amnesia
Dystopian
Memory Manipulation
Body Swapping
Philosophy
Band
Surreal Comedy
Parody
Metal Music
College
Magic
Isekai
Tsundere
Female Harem
Heterosexual
Tsundere
Shoujo
Love Triangle
Coming of Age
Heterosexual
Tragedy
Anti-Hero
Female Protagonist
Revenge
Super Power
Kaiju
Super Robot
Denpa
Military
Cosmic Horror
Mafia
Ensemble Cast
Historical
Crime
Primarily Adult Cast
Gods
Male Protagonist
School
Memory Manipulation
Shrine Maiden
Card Battle
Urban Fantasy
Shounen
Cyberpunk
Motorcycles
Alternate Universe
Coming of Age
School
Female Harem
Nudity
Super Power
Primarily Female Cast
Male Protagonist
Youkai
Iyashikei
Episodic
Male Protagonist
Found Family
Crime
Fugitive
Tanned Skin
Female Protagonist
Gangs
Coming of Age
Robots
Desert
Dystopian
Super Robot
Shounen
Pirates
Super Power
Primarily Adult Cast
Primarily Male Cast
Ensemble Cast
Military
War
Super Power
Love Triangle
Family Life
Coming of Age
Tragedy
Parenthood
Urban Fantasy
Super Power
Crime
Police
Urban Fantasy
Parody
Super Power
Post-Apocalyptic
Military
Female Harem
Swordplay
School
Vampire
Female Harem
Monster Girl
Witch
Tsundere
Love Triangle
Primarily Teen Cast
School
Heterosexual
Amnesia
Super Power
Female Protagonist
Primarily Adult Cast
Dissociative Identities
Female Protagonist
Philosophy
Super Power
Achronological Order
Magic
Primarily Teen Cast
Female Protagonist
School
Urban Fantasy
School Club
Shounen
Ninja
Super Power
Terrorism
War
Parody
Female Protagonist
Ensemble Cast
Surreal Comedy
Primarily Female Cast
Shounen
Magic
Guns
Female Protagonist
Youkai
Space
Super Robot
Super Power
Coming of Age
Philosophy
Magic
Super Power
Urban Fantasy
Urban
Tsundere
Female Harem
Heterosexual
Nudity
Idol
Musical Theater
Acting
Revenge
Female Protagonist
Urban
Work
Urban Fantasy
Tragedy
Female Protagonist
Super Power
Gore
Vampire
Shoujo
Urban Fantasy
Incest
Boarding School
Heterosexual
Tragedy
Rape
Age Gap
Female Protagonist
Shounen
Super Power
Swordplay
Male Protagonist
Memory Manipulation
Tragedy
Achronological Order
Witch
Death Game
Magic
Butler
Tragedy
Crime
Demons
Revenge
Memory Manipulation
Conspiracy
Urban Fantasy
Male Protagonist
Hikikomori
Post-Apocalyptic
Philosophy
Dystopian
Robots
Super Power
Female Harem
Shounen
Martial Arts
Male Protagonist
Heterosexual
Parody
School
Crossdressing
Ojou-sama
Female Protagonist
Baseball
Gambling
Philosophy
Seinen
Primarily Male Cast
Inseki
Female Harem
Twins
Nudity
Heterosexual
Parody
Historical
Slapstick
Primarily Male Cast
Educational
Youkai
Ensemble Cast
Urban Fantasy
Surreal Comedy
Male Protagonist
Alchemy
Conspiracy
Military
War
Tragedy
Denpa
Chuunibyou
Tragedy
Crime
Urban
Magic
Primarily Female Cast
Super Power
Amnesia
Achronological Order
Anti-Hero
Drugs
Female Protagonist
Crime
Philosophy
Football
Super Power
Kids
Primarily Teen Cast
Male Protagonist
Boxing
Shounen
Primarily Male Cast
Ensemble Cast
Youkai
Episodic
Iyashikei
Male Protagonist
Mythology
Economics
Historical
Heterosexual
Kemonomimi
Primarily Adult Cast
Female Protagonist
Terrorism
Urban
Assassins
Foreign
Male Protagonist
Amnesia
Shounen
Fairy Tale
Time Skip
Amnesia
Primarily Adult Cast
Urban
Terrorism
Death Game
Female Harem
Nudity
Aliens
Episodic
Slapstick
Female Protagonist
Reincarnation
Episodic
Magic
Heterosexual
Cute Girls Doing Cute Things
School Club
Band
Primarily Female Cast
Female Protagonist
Family Life
Virtual World
Artificial Intelligence
Ensemble Cast
Software Development
Amnesia
Anti-Hero
Assassins
Noir
Mafia
Isekai
Female Harem
School
CGI
Guns
Parody
School
Female Harem
Otaku Culture
Primarily Teen Cast
Swordplay
Demons
Magic
Nudity
Female Protagonist
Angels
School Club
Slavery
School
Aliens
Kemonomimi
Heterosexual
Foreign
Female Protagonist
Economics
Shounen
Super Power
Henshin
Primarily Male Cast
Male Protagonist
Shoujo
Female Protagonist
Coming of Age
School
Primarily Teen Cast
Female Harem
School
Male Protagonist
Nudity
Maids
Henshin
Gender Bending
School
Female Harem
Primarily Female Cast
Urban
Survival
Female Protagonist
Primarily Child Cast
Tragedy
Super Power
Urban
Primarily Female Cast
Female Protagonist
Urban Fantasy
Ninja
Shounen
Super Power
Male Protagonist
Coming of Age
School
Alternate Universe
Love Triangle
Twins
Memory Manipulation
Conspiracy
Amnesia
Primarily Adult Cast
Urban
Animals
Female Harem
Nekomimi
Male Protagonist
Love Triangle
Female Protagonist
Super Power
Fugitive
Rural
Police
Cars
Primarily Adult Cast
Male Protagonist
Space
Aliens
Super Power
Yandere
Urban Fantasy
Demons
Gore
Magic
Shounen
Fairy Tale
Found Family
Ensemble Cast
Historical
Youkai
Demons
Swordplay
Time Manipulation
Classic Literature
Tragedy
Philosophy
Anthology
Historical
Revenge
Fugitive
Crime
Desert
Male Protagonist
Guns
Gore
Noir
Revenge
Seinen
Nudity
Female Harem
Super Power
Male Protagonist
Primarily Female Cast
Ensemble Cast
Seinen
Tragedy
Coming of Age
Delinquents
Nekomimi
Kemonomimi
Female Harem
Aliens
Heterosexual
Demons
Nekomimi
Kemonomimi
Kuudere
Female Harem
School
Surreal Comedy
Meta
Super Power
Parody
Nudity
Lactation
Super Power
Male Protagonist
Gender Bending
Afterlife
Tragedy
School
Amnesia
Primarily Teen Cast
Swordplay
Martial Arts
Tragedy
Historical
Samurai
Demons
Butler
Shounen
Male Protagonist
Historical
Urban Fantasy
Gangs
Urban
Ensemble Cast
Dullahan
Vampire
Urban Fantasy
Amnesia
Werewolf
Heterosexual
Super Power
Urban Fantasy
Anti-Hero
War
Female Protagonist
Post-Apocalyptic
Military
Female Protagonist
Cute Girls Doing Cute Things
Primarily Female Cast
Cute Girls Doing Cute Things
Primarily Female Cast
Band
School Club
Female Protagonist
Prison
Tragedy
Survival
Super Power
Gore
Magic
Urban Fantasy
Male Protagonist
Witch
Super Power
Dissociative Identities
Philosophy
Urban Fantasy
Primarily Adult Cast
Female Protagonist
Restaurant
Work
Heterosexual
Ensemble Cast
Male Protagonist
Shoujo
Female Protagonist
School
Maids
Work
Magic
School
Female Harem
Tsundere
Nudity
Nudity
Butler
Ojou-sama
Maids
Tsundere
Alternate Universe
Primarily Teen Cast
Time Manipulation
Memory Manipulation
Philosophy
Tragedy
Survival
Super Power
Anti-Hero
Fugitive
Parody
Swordplay
Anachronism
Meta
Primarily Male Cast
Male Protagonist
Shounen
Urban Fantasy
Super Power
Demons
Inseki
Female Harem
Twins
Love Triangle
Nudity
Surreal Comedy
Seinen
Ensemble Cast
Philosophy
Male Protagonist
Work
Writing
Drawing
Coming of Age
Ensemble Cast
Rural
Family Life
Classic Literature
Female Protagonist
Coming of Age
Vampire
Survival
Tragedy
Rural
Anti-Hero
Parody
School
Heterosexual
Tomboy
Meta
Coming of Age
College
Surreal Comedy
Time Loop
Philosophy
Cute Girls Doing Cute Things
School Club
Primarily Female Cast
Female Protagonist
Band
Female Protagonist
School
Tsundere
Photography
Seinen
Zombie
Survival
Pandemic
Gore
Conspiracy
Magic
War
Rape
Swordplay
Politics
Josei
Slapstick
Female Protagonist
Crossdressing
Primarily Adult Cast
Male Protagonist
Suicide
Philosophy
Family Life
Reincarnation
Shounen
Super Power
Ninja
Time Manipulation
Robots
Shounen
Afterlife
Super Power
Male Protagonist
Female Protagonist
Henshin
Nudity
Samurai
Male Protagonist
Primarily Female Cast
Rural
Artificial Intelligence
Female Harem
Nudity
School Club
Urban Fantasy
Mythology
Achronological Order
Delinquents
Gangs
Masochism
School
Slapstick
Love Triangle
Heterosexual
Detective
Crime
Foreign
Historical
Female Protagonist
LGBTQ+ Themes
Transgender
Coming of Age
Gender Bending
Female Protagonist
Shounen
Time Manipulation
Gods
Battle Royale
Yandere
School
Super Power
Love Triangle
Surreal Comedy
Femboy
Video Games
Episodic
Meta
Otaku Culture
Male Protagonist
Monster Girl
Episodic
Slapstick
Female Protagonist
Coastal
Tsundere
Guns
School
Urban Fantasy
Female Harem
School
Primarily Female Cast
Heterosexual
School Club
Parody
School
Ensemble Cast
Male Protagonist
Heterosexual
Primarily Female Cast
Otaku Culture
Heterosexual
Tsundere
Incest
Urban
Parody
Female Protagonist
Satire
Episodic
Angels
Urban Fantasy
Zombie
Female Harem
Henshin
Male Protagonist
Urban Fantasy
Magic
Foreign
Episodic
Female Protagonist
Urban Fantasy
Magic
Super Power
Slapstick
Kuudere
Female Harem
Male Protagonist
School
Robots
Real Robot
School
Afterlife
Survival
Ensemble Cast
Slapstick
Surreal Comedy
Denpa
Female Protagonist
Heterosexual
Episodic
Primarily Child Cast
Episodic
Male Protagonist
Kids
Female Protagonist
Magic
Alchemy
Shounen
Male Protagonist
Super Power
Female Harem
School
Surreal Comedy
Nudity
Episodic
Time Manipulation
Alternate Universe
Time Loop
Conspiracy
Tragedy
Work
Female Protagonist
Coming of Age
Heterosexual
Rural
Dragons
Magic
School
Monster Girl
Female Harem
Shoujo
Family Life
Maids
Kuudere
Female Protagonist
Female Protagonist
Male Protagonist
Gore
Seinen
Nudity
Denpa
Chuunibyou
Wrestling
Feet
Male Protagonist
Demons
Delinquents
Male Protagonist
School
Shounen
Female Harem
Survival
Drugs
Coastal
Pandemic
Cute Girls Doing Cute Things
Female Protagonist
Band
Foreign
Coming of Age
Shoujo
School
Female Protagonist
Love Triangle
Heterosexual
Cute Girls Doing Cute Things
Band
School
Primarily Female Cast
Female Protagonist
Succubus
Isekai
Age Gap
Primarily Female Cast
Heterosexual
Magic
Tragedy
Female Protagonist
Cosmic Horror
Witch
Mythology
Lost Civilization
Gods
Philosophy
Female Protagonist
School Club
School
Meta
Slapstick
Male Protagonist
Demons
Shounen
Super Power
Youkai
Male Protagonist
Boys' Love
Primarily Adult Cast
Primarily Male Cast
Time Skip
LGBTQ+ Themes
Nudity
Female Harem
School
Super Power
Primarily Female Cast
Superhero
Super Power
Revenge
Henshin
Tokusatsu
Parody
Found Family
Swordplay
Slapstick
Male Protagonist
Shounen
Episodic
Nudity
Magic
Swimming
Coming of Age
Tragedy
Ghost
Rehabilitation
Hikikomori
Parody
Crossover
Nekomimi
Surreal Comedy
Vampire
Male Protagonist
Urban
Otaku Culture
Heterosexual
Foreign
School
Historical
Shoujo
Primarily Teen Cast
Coastal
Work
Meta
Male Protagonist
Love Triangle
Drawing
School
Afterlife
Tragedy
Male Protagonist
Kuudere
Rural
Heterosexual
Male Protagonist
School
Female Harem
Male Protagonist
Video Games
Demons
Ensemble Cast
Shounen
Battle Royale
Magic
Mythology
Tragedy
Ensemble Cast
Butler
Crossdressing
School
Primarily Female Cast
Ojou-sama
School
Shounen
Heterosexual
School Club
Female Harem
Kemonomimi
Magic
Isekai
Battle Royale
Female Harem
Dystopian
Conspiracy
Male Protagonist
LGBTQ+ Themes
Time Skip
Iyashikei
Found Family
Family Life
Adoption
Orphan
Economics
Super Power
Primarily Adult Cast
Male Protagonist
Conspiracy
Surreal Comedy
Episodic
Slapstick
School
Female Protagonist
Female Harem
School
Super Power
Satire
Nudity
Gambling
Seinen
Primarily Adult Cast
Primarily Male Cast
Male Protagonist
Idol
Primarily Female Cast
Ensemble Cast
Work
Found Family
Idol
Primarily Male Cast
Male Harem
Primarily Teen Cast
Urban
Iyashikei
Episodic
Youkai
Male Protagonist
Adoption
Battle Royale
Food
Male Protagonist
Twins
Primarily Teen Cast
Female Harem
School
School Club
Heterosexual
Nudity
Coming of Age
Youkai
Ghost
Tragedy
Rural
Politics
Ensemble Cast
Anachronism
Super Robot
Female Harem
School
Cute Boys Doing Cute Things
Primarily Male Cast
Iyashikei
Femboy
Female Protagonist
Swordplay
Vampire
Memory Manipulation
Monster Girl
Cute Girls Doing Cute Things
Primarily Female Cast
School Club
School
Yuri
Restaurant
Work
Ensemble Cast
Heterosexual
Male Protagonist
Hikikomori
Crime
Detective
Philosophy
Yakuza
Primarily Female Cast
Female Harem
Male Protagonist
Urban Fantasy
Anti-Hero
Crime
Detective
Super Power
Mythology
Male Protagonist
Ninja
Shounen
Super Power
Crime
Male Protagonist
Battle Royale
Death Game
Survival
Yandere
Tragedy
Surreal Comedy
Slapstick
Episodic
Female Protagonist
Primarily Female Cast
School
School Club
Male Protagonist
Female Harem
Primarily Female Cast
Philosophy
Found Family
Family Life
Coming of Age
Tragedy
Super Power
Terrorism
Dystopian
Pandemic
Post-Apocalyptic
Detective
Dystopian
Urban
Monster Boy
Work
Karuta
Female Protagonist
School Club
Josei
Coming of Age
Shounen
Super Power
Male Protagonist
Tragedy
Travel
Food
School
Tsundere
Male Protagonist
Primarily Teen Cast
Shounen
Super Power
Martial Arts
Aliens
Male Protagonist
Post-Apocalyptic
Time Skip
LGBTQ+ Themes
Male Protagonist
Super Robot
Military
War
Super Robot
Female Protagonist
Male Protagonist
War
Male Protagonist
Military
Primarily Adult Cast
Swordplay
Satire
Fairy
Post-Apocalyptic
Surreal Comedy
Achronological Order
Female Harem
Zombie
Male Protagonist
Ninja
Primarily Female Cast
Heterosexual
Tsundere
Male Protagonist
Chuunibyou
Female Protagonist
Youkai
Tsundere
Female Protagonist
Reincarnation
Urban Fantasy
Assassins
Cute Girls Doing Cute Things
Female Protagonist
Primarily Female Cast
School
Tragedy
Primarily Teen Cast
School
Gore
Memory Manipulation
Family Life
Adoption
Tragedy
Primarily Female Cast
Parenthood
School
Heterosexual
Male Protagonist
Alternate Universe
Primarily Female Cast
Primarily Female Cast
Alternate Universe
Female Protagonist
CGI
Body Swapping
Magic
Isekai
Tsundere
Love Triangle
Female Harem
Love Triangle
Ensemble Cast
Heterosexual
Coming of Age
Primarily Teen Cast
Zombie
Monster Girl
Ojou-sama
Heterosexual
Tragedy
Time Manipulation
Heterosexual
Memory Manipulation
Alternate Universe
Female Protagonist
Urban Fantasy
Surreal Comedy
Ensemble Cast
Primarily Female Cast
Philosophy
Nudity
Female Harem
Urban Fantasy
Primarily Female Cast
Male Protagonist
Demons
Vampire
Afterlife
Ghost
Delinquents
Iyashikei
Youkai
Male Protagonist
Adoption
Bullying
Tragedy
Female Protagonist
Twins
Cute Girls Doing Cute Things
Primarily Female Cast
School
Shounen
Super Power
Urban Fantasy
Anti-Hero
Demons
Shounen
Urban Fantasy
Magic
Exorcism
Death Game
Battle Royale
Tragedy
Magic
Mythology
Magic
Super Power
Urban Fantasy
Male Protagonist
Idol
Henshin
Primarily Female Cast
Super Power
Primarily Teen Cast
Female Protagonist
Virtual World
Death Game
Video Games
Male Protagonist
Swordplay
Virtual World
Video Games
Henshin
Netorare
Heterosexual
School
Super Power
Martial Arts
Female Protagonist
Primarily Teen Cast
Basketball
Male Protagonist
Shounen
Primarily Male Cast
School Club
Parody
Surreal Comedy
Meta
Tsundere
Aliens
School
Episodic
Primarily Male Cast
Slapstick
Satire
School
Coming of Age
Body Swapping
School Club
Urban Fantasy
Historical
Isekai
Military
Primarily Female Cast
Samurai
Magic
Tragedy
Primarily Female Cast
Female Protagonist
Philosophy
Magic
Tragedy
Time Manipulation
Female Protagonist
Philosophy
Alternate Universe
Anti-Hero
Memory Manipulation
Magic
Tragedy
Space
Space Opera
Aliens
Military
Primarily Adult Cast
War
CGI
Military
Historical
Foreign
Magic
Shounen
Male Protagonist
Lost Civilization
Female Protagonist
Swordplay
War
Military
Seinen
Demons
Cosmic Horror
Tragedy
Fugitive
Gore
Seinen
School
Primarily Female Cast
Male Protagonist
Politics
School Club
School Club
Detective
School
Primarily Teen Cast
Male Protagonist
Slapstick
School
Iyashikei
Nekomimi
Seinen
Female Harem
Magic
Mythology
Gods
Urban Fantasy
Parenthood
Family Life
Werewolf
Coming of Age
Shapeshifting
Writing
Drawing
Coming of Age
Meta
Work
Cute Girls Doing Cute Things
Primarily Female Cast
School
Slapstick
Yuri
Guns
Military
Female Protagonist
Anti-Hero
Seinen
Space
Work
Seinen
Primarily Adult Cast
Ensemble Cast
Ghost
Amnesia
School Club
Heterosexual
Tragedy
Coming of Age
School
Kuudere
Heterosexual
Female Protagonist
Lost Civilization
Post-Apocalyptic
Dystopian
Female Protagonist
Heterosexual
Coming of Age
Band
Love Triangle
Josei
Jazz Music
Nudity
Henshin
Female Harem
Primarily Teen Cast
Magic
Cute Girls Doing Cute Things
Meta
Surreal Comedy
Primarily Female Cast
Parody
Nudity
Demons
Heterosexual
Tentacles
Female Harem
Pirates
Shounen
Male Protagonist
Super Power
Ships
Fishing
Coming of Age
Aliens
Male Protagonist
Cute Boys Doing Cute Things
School
Shounen
Primarily Male Cast
Slapstick
Male Protagonist
Male Harem
Artificial Intelligence
Surreal Comedy
Primarily Male Cast
Female Protagonist
Class Struggle
Dystopian
Post-Apocalyptic
Lost Civilization
Philosophy
Magic
School
Male Protagonist
Super Power
Primarily Female Cast
Shounen
Super Power
Male Protagonist
Primarily Male Cast

In [129]:
indices.to_csv("indices.csv", index=True)

In [130]:
indices

,Unnamed: 0,title_romaji,coverImage_large,id,genres,tags,Boxing,Coming of Age,Delinquents,Tragedy,...,Romance,Mystery,Fantasy,Horror,Supernatural,Psychological,Music,Ecchi,Mahou Shoujo,Thriller
0,0,Ashita no Joe,https://s4.anilist.co/file/anilistcdn/media/an...,2402,"[Action, Drama, Slice of Life, Sports]","[Boxing, Coming of Age, Delinquents, Tragedy, ...",90,90,87,83,...,0,0,0,0,0,0,0,0,0,0
1,1,Lupin III,https://s4.anilist.co/file/anilistcdn/media/an...,1412,"[Adventure, Comedy]","[Seinen, Anti-Hero, Fugitive, Episodic, Crime]",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,Kidou Senshi Gundam,https://s4.anilist.co/file/anilistcdn/media/an...,80,"[Drama, Mecha, Sci-Fi]","[War, Military, Real Robot, Space, Space Opera]",0,80,0,80,...,0,0,0,0,0,0,0,0,0,0
3,3,Versailles no Bara,https://s4.anilist.co/file/anilistcdn/media/an...,338,"[Adventure, Drama, Romance]","[Historical, Royal Affairs, Class Struggle, Tr...",0,0,0,97,...,1,0,0,0,0,0,0,0,0,0
4,4,Lupin III: Cagliostro no Shiro,https://s4.anilist.co/file/anilistcdn/media/an...,1430,"[Action, Adventure, Comedy, Mystery]","[Crime, Conspiracy, Fugitive, Anti-Hero, Foreign]",0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2148,2148,Sozai Saishuka no Isekai Ryokouki,https://s4.anilist.co/file/anilistcdn/media/an...,187663,"[Adventure, Comedy, Fantasy, Slice of Life]","[Isekai, Creature Taming, Male Protagonist, Ma...",0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2149,2149,Mikata ga Yowasugite Hojo Mahou ni Tesshiteita...,https://s4.anilist.co/file/anilistcdn/media/an...,188487,"[Action, Adventure, Fantasy]","[Magic, Dungeon, Swordplay, Male Protagonist, ...",0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
2150,2150,Dr. STONE: SCIENCE FUTURE Part 2,https://s4.anilist.co/file/anilistcdn/media/an...,189117,"[Action, Adventure, Comedy, Sci-Fi]","[Post-Apocalyptic, Ensemble Cast, Male Protago...",0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2151,2151,Towa no Yuugure,https://s4.anilist.co/file/anilistcdn/media/an...,195153,"[Action, Drama, Romance, Sci-Fi]","[Robots, Heterosexual, Female Harem, Dystopian...",0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
2152,2152,Fujimoto Tatsuki 17-26,https://s4.anilist.co/file/anilistcdn/media/an...,198188,"[Action, Comedy, Drama, Romance, Sci-Fi, Slice...","[Episodic, Anthology, Surreal Comedy, Urban Fa...",0,0,0,0,...,1,0,0,0,1,0,0,0,0,0

In [131]:
def get_recommendations(title, a_list, cosine_sim=cosine_sim, num_recommend = 10):
    if title in df['title_romaji'].values:
        num_recd = 0
        raw_recd = 1
        top_similar = []
        idx = indices.index[indices['title_romaji'] == title].values[0]
        sim_scores = list(enumerate(cosine_sim[idx]))
        sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
        while num_recd <= num_recommend:
            top_rec = sim_scores[raw_recd]
            if df['title_romaji'].iloc[top_rec[0]] not in a_list and "Season" not in df['title_romaji'].iloc[top_rec[0]]:
                top_similar.append(sim_scores[raw_recd])
                num_recd += 1
            raw_recd += 1
        movie_indices = [i[0] for i in top_similar]
        return df['title_romaji'].iloc[movie_indices]

In [132]:
indices[indices['title_romaji'] == "Haikyuu!!"]['title_romaji'].values[0]

'Haikyuu!!'

In [133]:
import requests
import json
query = '''
query ($type: MediaType!, $userName: String!) {
  MediaListCollection(type: $type, userName: $userName) {
    lists {
      name
      entries {
        id
        media {
          title {
            romaji
          }
        }
      }
    }
  }
}
'''

variables = {
    'type': 'ANIME',
    'userName':'aryantestlist'
}

url = 'https://graphql.anilist.co'

response = requests.post(url, json={'query': query, 'variables': variables})

In [134]:
json_data = json.loads(response.content)
anime_list = []
for j in json_data['data']['MediaListCollection']['lists']:
    if j['name'] != "Dropped" and j['name'] != "Planning":
        for show in j['entries']:
            anime_list.append(str(show['media']['title']['romaji']))

In [135]:
for show in anime_list:
    if show not in df['title_romaji'].values:
        print(show)
        anime_list.remove(show)

Jujutsu Kaisen: Shimetsu Kaiyuu - Zenpen
Shoushimin Series 2nd Season
Kill Ao

In [136]:
total_recs = {}
for title in anime_list:  
    recs = list(get_recommendations(title, anime_list, num_recommend = 10))
    for rec in recs:
        if rec not in anime_list:
            if rec in total_recs:
                total_recs[rec] += recs.index(rec)
            else:
                total_recs[rec] = recs.index(rec)

In [137]:
dict(sorted(total_recs.items(), key=lambda item: item[1], reverse=True))

{'Tokyo Revengers: Tenjiku-hen': 55,
 'VINLAND SAGA': 41,
 'Bakuten!!': 35,
 'Summer Time Render': 35,
 'Hagane no Renkinjutsushi: FULLMETAL ALCHEMIST': 34,
 'Overlord III': 34,
 'Shinsekai yori': 32,
 'Code Geass: Hangyaku no Lelouch R2': 30,
 'Ima, Soko ni Iru Boku': 29,
 'Enen no Shouboutai: San no Shou': 28,
 'Shingeki no Kyojin Gaiden: Kuinaki Sentaku': 27,
 'Free!': 26,
 'PLUTO': 26,
 'Tougen Anki': 25,
 'CLANNAD': 25,
 'ONE PIECE': 24,
 'Yuuki Yuuna wa Yuusha de Aru': 23,
 'Sentai Daishikkaku': 22,
 'Shakunetsu Kabaddi': 20,
 'Shin Seiki Evangelion Movie: Air / Magokoro wo, Kimi ni': 20,
 'Haikyuu!! Riku VS Kuu': 19,
 'Eyeshield 21': 19,
 'Inuyashiki': 19,
 'Kimetsu no Yaiba: Mugenjou-hen Movie 1 - Akaza Sairai': 19,
 'Higurashi no Naku Koro ni Kai': 19,
 'Diamond no Ace': 18,
 'Katekyou Hitman REBORN!': 18,
 'Code Geass: Hangyaku no Lelouch': 18,
 'Magi: The kingdom of magic': 18,
 'Go-toubun no Hanayome Movie': 17,
 'Higurashi no Naku Koro ni Gou': 17,
 'Sakigake!! Cromartie Koukou': 16,
 'One Punch Man': 16,
 'Jujutsu Kaisen 0': 16,
 'Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e': 16,
 'Cowboy Bebop': 15,
 'Joker Game': 15,
 'Tokyo Revengers': 15,
 'No Game No Life Zero': 15,
 'Kuroko no Basket 2nd SEASON': 14,
 'Gintama': 14,
 'Vivy: Fluorite Eye’s Song': 14,
 'Kaijuu 8-gou': 14,
 'Kiseijuu: Sei no Kakuritsu': 14,
 'Tsurezure Children': 14,
 'Seishun Buta Yarou wa Yumemiru Shoujo no Yume wo Minai': 14,
 'Dandadan': 13,
 'MONSTER': 13,
 'Gachiakuta': 13,
 'Shin Seiki Evangelion': 13,
 'Darling in the Franxx': 13,
 'Boku no Hero Academia': 13,
 'Higurashi no Naku Koro ni': 13,
 'Haikyuu!!: Gomi Suteba no Kessen': 12,
 'Sword Art Online: Alicization': 12,
 'JIN-ROH': 12,
 '91Days': 12,
 'Kaguya-sama wa Kokurasetai: Ultra Romantic': 12,
 'Make Heroine ga Oosugiru!': 12,
 'Higurashi no Naku Koro ni Sotsu': 12,
 'Kimi wo Aishita Hitori no Boku e': 12,
 'Yahari Ore no Seishun Love Come wa Machigatteiru. Zoku': 11,
 'Ouran Koukou Host Club': 10,
 'Haikyuu!! TO THE TOP 2': 10,
 'Zoku Sayonara Zetsubou Sensei': 10,
 'Shimoneta to Iu Gainen ga Sonzai Shinai Taikutsu na Sekai': 10,
 'Enen no Shouboutai': 10,
 'My Home Hero': 10,
 'Chobits': 10,
 'Hametsu no Oukoku': 10,
 'Shoujo Kakumei Utena': 10,
 'Little Busters!': 10,
 'K-ON!!': 10,
 'Giji Harem': 10,
 'Ginga Eiyuu Densetsu': 10,
 'Hi Score Girl II': 10,
 'Golden Time': 10,
 'Mato Seihei no Slave': 10,
 'Punch Line': 10,
 'Inazuma Eleven': 10,
 'Blue Lock VS. U-20 JAPAN': 9,
 'Scott Pilgrim Takes Off': 9,
 'Kuroko no Basket: Last Game': 9,
 'ID: INVADED': 9,
 'Yuukoku no Moriarty Part 2': 9,
 'GHOST IN THE SHELL: Koukaku Kidoutai': 9,
 'Munou na Nana': 9,
 'School Rumble': 9,
 'Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen': 9,
 'Suzumiya Haruhi no Yuuutsu (2009)': 9,
 'Persona 4 the Animation': 9,
 'Shiguang Dailiren II': 9,
 'HUNTER×HUNTER: THE LAST MISSION': 9,
 'Shikanoko Nokonoko Koshitantan': 8,
 'Danshi Koukousei no Nichijou': 8,
 'Black Clover': 8,
 'Boku no Hero Academia 6': 8,
 'Babylon': 8,
 'Meitantei Conan': 8,
 'NARUTO: Shippuuden': 8,
 'orange': 8,
 'Kaguya-sama wa Kokurasetai?: Tensaitachi no Renai Zunousen': 8,
 'Ijiranaide, Nagatoro-san': 8,
 'Yojouhan Shinwa Taikei': 8,
 'SANDA': 8,
 'Komi-san wa, Komyushou desu.': 8,
 'Kaguya-sama wa Kokurasetai: First Kiss wa Owaranai': 8,
 'Suzumiya Haruhi no Yuuutsu': 8,
 'Kokoro Connect': 8,
 'Kono Yo no Hate de Koi wo Utau Shoujo YU-NO': 8,
 'Mahou Shoujo Madoka☆Magica: Hangyaku no Monogatari': 8,
 'Haikyuu!! TO THE TOP': 7,
 'Boku no Hero Academia FINAL SEASON': 7,
 'Mahou Shoujo Ikusei Keikaku': 7,
 'DEVILMAN crybaby': 7,
 'Shingeki no Kyojin: Chronicle': 7,
 'Terra Formars': 7,
 'Kami nomi zo Shiru Sekai II': 7,
 'GOSICK': 7,
 'Code Geass: Dakkan no Rozé': 7,
 'Boku no Kokoro no Yabai Yatsu': 7,
 'Jibaku Shounen Hanako-kun': 7,
 'Hikaru ga Shinda Natsu': 7,
 'Little Busters!: Refrain': 7,
 'Kaze ga Tsuyoku Fuiteiru': 7,
 'Baka to Test to Shoukanjuu': 6,
 'Kimi no Koto ga Dai Dai Dai Dai Daisuki na 100-nin no Kanojo': 6,
 'Ao no Exorcist': 6,
 'Mousou Dairinin': 6,
 'Blue Archive The Animation': 6,
 'Gungrave': 6,
 'Yahari Ore no Seishun Love Come wa Machigatteiru.': 6,
 'Tokidoki Bosotto Rossiya-go de Dereru Tonari no Alya-san': 6,
 'Kowloon Generic Romance': 6,
 'Yuukoku no Moriarty': 6,
 'Ano Hi Mita Hana no Namae wo Bokutachi wa Mada Shiranai.': 6,
 'Aharen-san wa Hakarenai': 6,
 'Shiguang Dailiren: Yingdu Pian': 6,
 'Shinmai Maou no Testament: Toujou Basara no Hard Sweet na Nichijou': 6,
 'Mushoku Tensei II: Isekai Ittara Honki Dasu': 6,
 'BLEACH': 5,
 'NieR:Automata Ver1.1a': 5,
 'Tate no Yuusha no Nariagari': 5,
 'Deadman Wonderland': 5,
 'Go-toubun no Hanayome': 5,
 'Akudama Drive': 5,
 'Berserk: Ougon Jidai-hen I - Haou no Tamago': 5,
 'Josee to Tora to Sakanatachi': 5,
 'Toradora!': 5,
 'Shiguang Dailiren': 5,
 'K': 5,
 'Aoashi': 5,
 'One Punch Man 3': 4,
 'ATRI: My Dear Moments': 4,
 "Wolf's Rain": 4,
 'Kenpuu Denki Berserk': 4,
 'Guilty Crown': 4,
 'Akiba Meido Sensou': 4,
 'Kimi no Suizou wo Tabetai': 4,
 'Dorohedoro': 4,
 'GANTZ': 4,
 'Mahou Shoujo Madoka☆Magica': 4,
 'Mushoku Tensei II: Isekai Ittara Honki Dasu Part 2': 4,
 'Saiki Kusuo no Ψ-nan: Ψ-shidou-hen': 3,
 'SLAM DUNK': 3,
 'PSYCHO-PASS': 3,
 'Kimi wa Houkago Insomnia': 3,
 'Poputepipikku': 2,
 'Ajin': 2,
 'Metallic Rouge': 2,
 'TEXHNOLYZE': 2,
 'Summer Pockets': 2,
 'Undead Girl Murder Farce': 2,
 'Kidou Senshi Gundam: Tekketsu no Orphans': 2,
 'Seishun Buta Yarou wa Odekake Sister no Yume wo Minai': 2,
 'Shinmai Maou no Testament': 2,
 'Boku no Hero Academia 4': 1,
 'BANANA FISH': 1,
 'Koe no Katachi': 1,
 'Suzumiya Haruhi no Shoushitsu': 1,
 'Blue Lock: EPISODE Nagi': 1,
 'Sayonara Zetsubou Sensei': 0,
 'Ahiru no Sora': 0,
 'Apocalypse Hotel': 0,
 'No Guns Life': 0,
 'Taishou Otome Otogibanashi': 0}

In [154]:
def find_similarity(title, a_list, cosine_sim=cosine_sim):
    idx = indices.index[indices['title_romaji'] == title].values[0]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    for j in sim_scores:
        if indices.iloc[j[0]]['title_romaji'] in a_list:
            print(indices.iloc[j[0]]['title_romaji'])
find_similarity('Tokyo Revengers: Tenjiku-hen', anime_list)

Jujutsu Kaisen 2nd Season
Cyberpunk: Edgerunners
Charlotte
Shingeki no Kyojin: The Final Season
Blue Lock
Haikyuu!!
Jujutsu Kaisen
Haikyuu!! 2nd Season
Shingeki no Kyojin Season 3 Part 2
Chainsaw Man
Shingeki no Kyojin
Shingeki no Kyojin: The Final Season Part 2
Shigatsu wa Kimi no Uso
Haikyuu!!: Karasuno Koukou VS Shiratorizawa Gakuen Koukou
Chainsaw Man: Reze-hen
Shoushimin Series
Steins;Gate
Angel Beats!
Kuroko no Basket
Re:Zero kara Hajimeru Isekai Seikatsu 2nd Season
Re:Zero kara Hajimeru Isekai Seikatsu
Shingeki no Kyojin: The Final Season - Kanketsu-hen Kouhen
Ansatsu Kyoushitsu
Shingeki no Kyojin Season 2
Shingeki no Kyojin Season 3
DEATH NOTE
86: Eighty Six
Plastic Memories
Ansatsu Kyoushitsu 2nd Season
Ao no Hako
Hyouka
Shingeki no Kyojin: The Final Season - Kanketsu-hen Zenpen
Kimi no Na wa.
86: Eighty Six Part 2
Saiki Kusuo no Ψ-nan 2
Saiki Kusuo no Ψ-nan

In [138]:
show_list = list(dict(sorted(total_recs.items(), key=lambda item: item[1], reverse=True)).keys())[0:10]
def find_similarity(title, a_list, cosine_sim=cosine_sim):
    idx = indices.index[indices['title_romaji'] == title].values[0]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    for j in sim_scores:
        if indices.iloc[j[0]]['title_romaji'] in a_list:
            print(indices.iloc[j[0]]['title_romaji'])
similarities = []
for j in show_list:
    similarities.append(find_similarity(j, anime_list))
json_response = []
for show in range(len(show_list)):
    json_response.append({"id": int(indices[indices['title_romaji'] == show_list[show]]['id'].values[0]), "name": show_list[show], "pic": indices[indices['title_romaji'] == show_list[show]]['coverImage_large'].values[0], 'genres':indices[indices['title_romaji'] == show_list[show]]['genres'].values[0], 'tags':indices[indices['title_romaji'] == show_list[show]]['tags'].values[0], 'similar':similarities[show]})
json.dumps(json_response)

'[{"id": 163329, "name": "Tokyo Revengers: Tenjiku-hen", "pic": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx163329-lGJRnYV9dcjc.jpg", "genres": ["Action", "Drama", "Romance", "Supernatural"], "tags": ["Primarily Teen Cast", "Shounen", "Revenge", "Gangs", "Male Protagonist"]}, {"id": 101348, "name": "VINLAND SAGA", "pic": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx101348-2fhDFPCuMNiz.jpg", "genres": ["Action", "Adventure", "Drama"], "tags": ["Vikings", "Revenge", "Foreign", "War", "Historical"]}, {"id": 125839, "name": "Bakuten!!", "pic": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx125839-ZaMryHrBBvXQ.png", "genres": ["Comedy", "Drama", "Sports"], "tags": ["Athletics", "Primarily Male Cast", "Primarily Teen Cast", "School Club", "Male Protagonist"]}, {"id": 129201, "name": "Summer Time Render", "pic": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx129201-HJBauga2be8I.png", "genres": ["Action", "Drama", "Mystery", "Supernatural", "Thriller"], "tags": ["Survival", "Time Manipulation", "Urban Fantasy", "Time Loop", "Primarily Teen Cast"]}, {"id": 5114, "name": "Hagane no Renkinjutsushi: FULLMETAL ALCHEMIST", "pic": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx5114-nSWCgQlmOMtj.jpg", "genres": ["Action", "Adventure", "Drama", "Fantasy"], "tags": ["Alchemy", "Conspiracy", "Military", "War", "Tragedy"]}, {"id": 101474, "name": "Overlord III", "pic": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx101474-tGRyvSAWMjU9.jpg", "genres": ["Action", "Adventure", "Fantasy"], "tags": ["Male Protagonist", "Kingdom Management", "Isekai", "Anti-Hero", "Magic"]}, {"id": 13125, "name": "Shinsekai yori", "pic": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx13125-2EDZb8ahshQc.png", "genres": ["Drama", "Horror", "Mystery", "Psychological", "Sci-Fi", "Supernatural"], "tags": ["Class Struggle", "Dystopian", "Post-Apocalyptic", "Lost Civilization", "Philosophy"]}, {"id": 2904, "name": "Code Geass: Hangyaku no Lelouch R2", "pic": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx2904-Fet9Q33suC7G.jpg", "genres": ["Action", "Drama", "Mecha", "Sci-Fi", "Thriller"], "tags": ["Anti-Hero", "War", "Military", "Class Struggle", "Revenge"]}, {"id": 160, "name": "Ima, Soko ni Iru Boku", "pic": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx160-t5rKPAhZoznO.jpg", "genres": ["Adventure", "Drama", "Fantasy", "Sci-Fi"], "tags": ["Tragedy", "Dystopian", "War", "Slavery", "Survival"]}, {"id": 149118, "name": "Enen no Shouboutai: San no Shou", "pic": "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/bx149118-AOQb0xuTssGl.jpg", "genres": ["Action", "Drama", "Sci-Fi", "Supernatural"], "tags": ["Post-Apocalyptic", "Cult", "Dystopian", "Conspiracy", "Super Power"]}]'

In [91]:
indices

,title_romaji,coverImage_large,id
0,Ashita no Joe,https://s4.anilist.co/file/anilistcdn/media/an...,2402
1,Lupin III,https://s4.anilist.co/file/anilistcdn/media/an...,1412
2,Kidou Senshi Gundam,https://s4.anilist.co/file/anilistcdn/media/an...,80
3,Versailles no Bara,https://s4.anilist.co/file/anilistcdn/media/an...,338
4,Lupin III: Cagliostro no Shiro,https://s4.anilist.co/file/anilistcdn/media/an...,1430
...,...,...,...
2148,Sozai Saishuka no Isekai Ryokouki,https://s4.anilist.co/file/anilistcdn/media/an...,187663
2149,Mikata ga Yowasugite Hojo Mahou ni Tesshiteita...,https://s4.anilist.co/file/anilistcdn/media/an...,188487
2150,Dr. STONE: SCIENCE FUTURE Part 2,https://s4.anilist.co/file/anilistcdn/media/an...,189117
2151,Towa no Yuugure,https://s4.anilist.co/file/anilistcdn/media/an...,195153
2152,Fujimoto Tatsuki 17-26,https://s4.anilist.co/file/anilistcdn/media/an...,198188